### PR TITLE
Fix URI malformed issue for links with percent symbol

### PR DESCRIPTION
**Pull request by andrey-hohlov**
Fix URI malformed issue for links with percent symbol
https://github.com/nmrugg/gulp-hash-src/issues/4
http://stackoverflow.com/questions/9064536/javascript-decodeuricomponent-malformed-uri-exception

### CODE REVIEW

**Comment by nmrugg** [comment]
Thanks for the PR. But it looks like we want `encodeURI()` not `encodeURIComponent()`. Can you fix that?

**Comment by andrey-hohlov** [comment]
Yes, we want encodeURI() - fixed

**Comment by nmrugg** [comment]
Great. Can you squash the commits for me?

**Comment by andrey-hohlov** [comment]
Done. Please check that everything I did right (not enough git expirience)

**Comment by nmrugg** [comment]
Perfect. But I'm a little busy now. I'll try to check it once more over the weekend and then merge.

**Comment by nmrugg** [comment]
I've been a little busy, and took me a bit to be able to sit down and think about this. Is it just me or does this now just undo the very thing it's supposed to be doing?

Correct me if I'm wrong, but it seems that the problem is that if we try to `decodeURI()` a string that has not been `encodeURI()`'ed, it may throw an error. So, it seems like what we should do is use a `try`/`catch` block to ignore a malformed (or non-`encodeURI()`'ed) string.

What do you think?

**Comment by andrey-hohlov** [comment]
Yes, problem with not-encoded url strings in this case.

We always need `decodeURI`'ed link, right?
I think we can replace code with `try/catch`. I test it with that link and it's work:

```
try {
        link = decodeURI(String(link));
    } catch (err) {
        // do nothing
    }
```

But can be any more links with another problem? Or can be problem in next step in this function? By the way we can solve this problem and waiting for another bug reports if exist another type of "bad" links.

In current case "bad" link just ignored, hash added to links before that in document, and links after that.

**Comment by nmrugg** [comment]
Sorry for the slow reply. I think the try/catch code you posted should work. I don't think there are other types of bad links. Do you want to update the PR?

**Comment by andrey-hohlov** [comment]
Thank you for reply! PR updated.

**Pull request merged**
